# Generated by Django 6.0.6 on 2026-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Hostel Owner'), ('admin', 'Website Admin')], default='student', max_length=10),
        ),
    ]
