# Generated by Django 6.0.6 on 2026-08-12 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_rename_price_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'hostel'), name='unique_pending_reservation_per_user_hostel'),
        ),
    ]
