# Generated by Django 4.2.13 on 2026-06-06 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=15)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hostels.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest', 'status'], name='bookings_bo_guest_i_261eaf_idx'), models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='bookings_bo_room_id_59e0a4_idx'), models.Index(fields=['status', 'check_in_date'], name='bookings_bo_status_4382c8_idx')],
            },
        ),
    ]
