# Generated by Django 6.0.6 on 2026-08-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_single_stay_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_guest_i_261eaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_room_id_59e0a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_4382c8_idx',
        ),
    ]
