# Generated by Django 4.2.13 on 2026-08-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_price_per_night_to_monthly_rent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_room_stay_date_active',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='stay_date',
            new_name='starting_date',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'checked_in'])), fields=('room', 'starting_date'), name='unique_room_starting_date_active'),
        ),
    ]
